"""
Script to seed the database with sample data
Run this to populate your database with test data
"""
from datetime import date, timedelta
from app.db.session import SessionLocal
from app.models.user import User
from app.models.listing import Listing

def seed_database():
    db = SessionLocal()
    
    try:
        # Check if data already exists
        existing_users = db.query(User).count()
        if existing_users > 0:
            print(f"Database already has {existing_users} users. Skipping seed.")
            print("If you want to re-seed, delete the database file and run create_tables.py first.")
            return
        
        print("Seeding database...")
        
        # Create sample users
        users = [
            User(
                auth0_user_id="auth0|seed_user_1",
                email="john.doe@example.com",
                first_name="John",
                last_name="Doe",
                profile_complete=True,
                is_active=True
            ),
            User(
                auth0_user_id="auth0|seed_user_2",
                email="jane.smith@example.com",
                first_name="Jane",
                last_name="Smith",
                profile_complete=True,
                is_active=True
            ),
            User(
                auth0_user_id="auth0|seed_user_3",
                email="mike.johnson@example.com",
                first_name="Mike",
                last_name="Johnson",
                profile_complete=True,
                is_active=True
            ),
            User(
                auth0_user_id="auth0|seed_user_4",
                email="sarah.williams@example.com",
                first_name="Sarah",
                last_name="Williams",
                profile_complete=True,
                is_active=True
            ),
        ]
        
        db.add_all(users)
        db.commit()
        print(f"✓ Created {len(users)} users")
        
        # Refresh users to get their IDs
        for user in users:
            db.refresh(user)
        
        # Create sample listings
        today = date.today()
        
        listings = [
            # Unit listings
            Listing(
                user_id=users[0].id,
                listing_type="unit",
                address="123 University Ave, Toronto, ON",
                num_rooms_available=2,
                total_rooms=2,
                num_bathrooms=2,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=30),
                end_date=today + timedelta(days=150),
                distance_to_university=5,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="Heat and Water",
                building_name="University Towers",
                images=["https://lh3.googleusercontent.com/p/AF1QipPdzsTQ9SSCMFD0xlq9CZYJVgvF_SDidpyXlrj2=s1360-w1360-h1020-rw", "https://www.society145.com/img/society-145-rendering.jpg"],
                unit_price=2400.00,
                total_ensuite=1,
                total_shared_bathrooms=1
            ),
            Listing(
                user_id=users[1].id,
                listing_type="unit",
                address="456 College St, Toronto, ON",
                num_rooms_available=3,
                total_rooms=3,
                num_bathrooms=2,
                furnished=False,
                ensuite=0,
                start_date=today + timedelta(days=15),
                end_date=today + timedelta(days=135),
                distance_to_university=10,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="None",
                building_name="College Plaza",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                unit_price=3200.00,
                total_ensuite=0,
                total_shared_bathrooms=2
            ),
            Listing(
                user_id=users[1].id,
                listing_type="unit",
                address="888 Queen St E, Toronto, ON",
                num_rooms_available=1,
                total_rooms=1,
                num_bathrooms=1,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=10),
                end_date=today + timedelta(days=130),
                distance_to_university=15,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="Heat and Water",
                building_name="Queen's Court",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                unit_price=1800.00,
                total_ensuite=1,
                total_shared_bathrooms=0
            ),
            Listing(
                user_id=users[2].id,
                listing_type="unit",
                address="200 St. George St, Toronto, ON",
                num_rooms_available=4,
                total_rooms=4,
                num_bathrooms=3,
                furnished=True,
                ensuite=2,
                start_date=today + timedelta(days=25),
                end_date=today + timedelta(days=145),
                distance_to_university=2,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="All Utilities",
                building_name="Campus Residence",
                images=["https://lh3.googleusercontent.com/p/AF1QipPdzsTQ9SSCMFD0xlq9CZYJVgvF_SDidpyXlrj2=s1360-w1360-h1020-rw", "https://www.society145.com/img/society-145-rendering.jpg"],
                unit_price=4500.00,
                total_ensuite=2,
                total_shared_bathrooms=1
            ),
            Listing(
                user_id=users[3].id,
                listing_type="unit",
                address="75 Harbord St, Toronto, ON",
                num_rooms_available=2,
                total_rooms=2,
                num_bathrooms=1,
                furnished=False,
                ensuite=0,
                start_date=today + timedelta(days=40),
                end_date=today + timedelta(days=160),
                distance_to_university=6,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="None",
                building_name="Harbord Apartments",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                unit_price=2100.00,
                total_ensuite=0,
                total_shared_bathrooms=1
            ),
            Listing(
                user_id=users[0].id,
                listing_type="unit",
                address="90 Wellesley St W, Toronto, ON",
                num_rooms_available=1,
                total_rooms=1,
                num_bathrooms=1,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=5),
                end_date=today + timedelta(days=125),
                distance_to_university=18,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="Heat and Water",
                building_name="Wellesley Heights",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                unit_price=1950.00,
                total_ensuite=1,
                total_shared_bathrooms=0
            ),
            Listing(
                user_id=users[1].id,
                listing_type="unit",
                address="350 Huron St, Toronto, ON",
                num_rooms_available=3,
                total_rooms=3,
                num_bathrooms=2,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=35),
                end_date=today + timedelta(days=155),
                distance_to_university=4,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="Heat and Water",
                building_name="Huron Place",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                unit_price=3100.00,
                total_ensuite=1,
                total_shared_bathrooms=1
            ),
            Listing(
                user_id=users[2].id,
                listing_type="unit",
                address="145 Charles St W, Toronto, ON",
                num_rooms_available=2,
                total_rooms=2,
                num_bathrooms=2,
                furnished=True,
                ensuite=2,
                start_date=today + timedelta(days=20),
                end_date=today + timedelta(days=140),
                distance_to_university=14,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="All Utilities",
                building_name="Charles Luxury Suites",
                images=["https://lh3.googleusercontent.com/p/AF1QipPdzsTQ9SSCMFD0xlq9CZYJVgvF_SDidpyXlrj2=s1360-w1360-h1020-rw", "https://www.society145.com/img/society-145-rendering.jpg"],
                unit_price=3800.00,
                total_ensuite=2,
                total_shared_bathrooms=0
            ),
            # Room listings
            Listing(
                user_id=users[2].id,
                listing_type="room",
                address="789 Bloor St W, Toronto, ON",
                num_rooms_available=1,
                total_rooms=4,
                num_bathrooms=2,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=45),
                end_date=today + timedelta(days=165),
                distance_to_university=8,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="All Utilities",
                building_name="Bloor Residences",
                images=["https://lh3.googleusercontent.com/p/AF1QipPdzsTQ9SSCMFD0xlq9CZYJVgvF_SDidpyXlrj2=s1360-w1360-h1020-rw", "https://www.society145.com/img/society-145-rendering.jpg"],
                price_per_room=1200.00,
                how_many_ensuite_rooms=1,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[3].id,
                listing_type="room",
                address="321 Spadina Ave, Toronto, ON",
                num_rooms_available=2,
                total_rooms=5,
                num_bathrooms=3,
                furnished=True,
                ensuite=0,
                start_date=today + timedelta(days=20),
                end_date=today + timedelta(days=140),
                distance_to_university=3,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="Heat and Water",
                building_name="Spadina House",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=950.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=3
            ),
            Listing(
                user_id=users[0].id,
                listing_type="room",
                address="555 Bay St, Toronto, ON",
                num_rooms_available=1,
                total_rooms=3,
                num_bathrooms=2,
                furnished=False,
                ensuite=1,
                start_date=today + timedelta(days=60),
                end_date=today + timedelta(days=180),
                distance_to_university=12,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="All Utilities",
                building_name="Bay Street Lofts",
                images=["https://lh3.googleusercontent.com/p/AF1QipPdzsTQ9SSCMFD0xlq9CZYJVgvF_SDidpyXlrj2=s1360-w1360-h1020-rw", "https://www.society145.com/img/society-145-rendering.jpg"],
                price_per_room=1500.00,
                how_many_ensuite_rooms=1,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[1].id,
                listing_type="room",
                address="432 Yonge St, Toronto, ON",
                num_rooms_available=1,
                total_rooms=3,
                num_bathrooms=1,
                furnished=True,
                ensuite=0,
                start_date=today + timedelta(days=12),
                end_date=today + timedelta(days=132),
                distance_to_university=20,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="None",
                building_name="Yonge Plaza",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=850.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[2].id,
                listing_type="room",
                address="67 St. George St, Toronto, ON",
                num_rooms_available=1,
                total_rooms=4,
                num_bathrooms=2,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=28),
                end_date=today + timedelta(days=148),
                distance_to_university=1,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="All Utilities",
                building_name="St. George Manor",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=1350.00,
                how_many_ensuite_rooms=1,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[3].id,
                listing_type="room",
                address="210 Brunswick Ave, Toronto, ON",
                num_rooms_available=2,
                total_rooms=6,
                num_bathrooms=3,
                furnished=False,
                ensuite=0,
                start_date=today + timedelta(days=50),
                end_date=today + timedelta(days=170),
                distance_to_university=7,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="Heat and Water",
                building_name="Brunswick House",
                images=["https://lh3.googleusercontent.com/p/AF1QipPdzsTQ9SSCMFD0xlq9CZYJVgvF_SDidpyXlrj2=s1360-w1360-h1020-rw", "https://www.society145.com/img/society-145-rendering.jpg"],
                price_per_room=800.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=3
            ),
            Listing(
                user_id=users[0].id,
                listing_type="room",
                address="88 Harbord St, Toronto, ON",
                num_rooms_available=1,
                total_rooms=2,
                num_bathrooms=1,
                furnished=True,
                ensuite=0,
                start_date=today + timedelta(days=8),
                end_date=today + timedelta(days=128),
                distance_to_university=5,
                gym_in_building=False,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="None",
                building_name="Harbord Commons",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=750.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[1].id,
                listing_type="room",
                address="512 College St, Toronto, ON",
                num_rooms_available=1,
                total_rooms=3,
                num_bathrooms=2,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=38),
                end_date=today + timedelta(days=158),
                distance_to_university=9,
                gym_in_building=True,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="All Utilities",
                building_name="College Heights",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=1100.00,
                how_many_ensuite_rooms=1,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[2].id,
                listing_type="room",
                address="299 Huron St, Toronto, ON",
                num_rooms_available=2,
                total_rooms=5,
                num_bathrooms=2,
                furnished=False,
                ensuite=0,
                start_date=today + timedelta(days=22),
                end_date=today + timedelta(days=142),
                distance_to_university=4,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="Heat and Water",
                building_name="Huron Gardens",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=900.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=2
            ),
            Listing(
                user_id=users[3].id,
                listing_type="room",
                address="155 Bedford Rd, Toronto, ON",
                num_rooms_available=1,
                total_rooms=4,
                num_bathrooms=3,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=55),
                end_date=today + timedelta(days=175),
                distance_to_university=11,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="All Utilities",
                building_name="Bedford Luxury Apartments",
                images=["https://lh3.googleusercontent.com/p/AF1QipPdzsTQ9SSCMFD0xlq9CZYJVgvF_SDidpyXlrj2=s1360-w1360-h1020-rw", "https://www.society145.com/img/society-145-rendering.jpg"],
                price_per_room=1600.00,
                how_many_ensuite_rooms=1,
                how_many_shared_bathrooms_in_apartment=2
            ),
            Listing(
                user_id=users[0].id,
                listing_type="room",
                address="42 Sussex Ave, Toronto, ON",
                num_rooms_available=1,
                total_rooms=3,
                num_bathrooms=1,
                furnished=True,
                ensuite=0,
                start_date=today + timedelta(days=18),
                end_date=today + timedelta(days=138),
                distance_to_university=6,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="None",
                building_name="Sussex Village",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=825.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[1].id,
                listing_type="room",
                address="333 Bloor St W, Toronto, ON",
                num_rooms_available=2,
                total_rooms=4,
                num_bathrooms=2,
                furnished=True,
                ensuite=0,
                start_date=today + timedelta(days=32),
                end_date=today + timedelta(days=152),
                distance_to_university=7,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="Heat and Water",
                building_name="Bloor Central",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=1050.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=2
            ),
            Listing(
                user_id=users[2].id,
                listing_type="room",
                address="678 Bathurst St, Toronto, ON",
                num_rooms_available=1,
                total_rooms=2,
                num_bathrooms=1,
                furnished=False,
                ensuite=0,
                start_date=today + timedelta(days=65),
                end_date=today + timedelta(days=185),
                distance_to_university=13,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="None",
                building_name="Bathurst Apartments",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=700.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[3].id,
                listing_type="room",
                address="91 Charles St E, Toronto, ON",
                num_rooms_available=1,
                total_rooms=3,
                num_bathrooms=2,
                furnished=True,
                ensuite=1,
                start_date=today + timedelta(days=42),
                end_date=today + timedelta(days=162),
                distance_to_university=16,
                gym_in_building=True,
                laundry_in_unit=True,
                laundry_in_building=False,
                utilities_included="All Utilities",
                building_name="Charles East Tower",
                images=["https://lh3.googleusercontent.com/p/AF1QipPdzsTQ9SSCMFD0xlq9CZYJVgvF_SDidpyXlrj2=s1360-w1360-h1020-rw", "https://www.society145.com/img/society-145-rendering.jpg"],
                price_per_room=1400.00,
                how_many_ensuite_rooms=1,
                how_many_shared_bathrooms_in_apartment=1
            ),
            Listing(
                user_id=users[0].id,
                listing_type="room",
                address="180 Madison Ave, Toronto, ON",
                num_rooms_available=2,
                total_rooms=5,
                num_bathrooms=3,
                furnished=False,
                ensuite=0,
                start_date=today + timedelta(days=15),
                end_date=today + timedelta(days=135),
                distance_to_university=8,
                gym_in_building=False,
                laundry_in_unit=False,
                laundry_in_building=True,
                utilities_included="Heat and Water",
                building_name="Madison Square",
                images=["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJF2tybvvwKAnFavpxVS_XgMkWawTRv3kNyA&s"],
                price_per_room=875.00,
                how_many_ensuite_rooms=0,
                how_many_shared_bathrooms_in_apartment=3
            ),
        ]
        
        db.add_all(listings)
        db.commit()
        print(f"✓ Created {len(listings)} listings")
        print("\n✅ Database seeded successfully!")
        print(f"   - {len(users)} users")
        print(f"   - {len(listings)} listings")
        
    except Exception as e:
        print(f"❌ Error seeding database: {e}")
        db.rollback()
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed_database()

